name: Publish TypeScript Package to NPM

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger for testing
    inputs:
      test_publish:
        description: 'Publish to NPM test registry'
        required: false
        default: false
        type: boolean

jobs:
  test-publish:
    if: github.event_name == 'workflow_dispatch' && inputs.test_publish == true
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/typescript
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: packages/typescript/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build package
      run: npm run build
    
    - name: Run tests
      run: npm test || echo "No tests found"
    
    - name: Lint code
      run: npm run lint || echo "No linting configured"
    
    - name: Dry run publish
      run: npm publish --dry-run
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  
  publish:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.test_publish == false)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/typescript
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
        cache-dependency-path: packages/typescript/package-lock.json
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build package
      run: npm run build
    
    - name: Run tests
      run: npm test || echo "No tests found"
    
    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    
    - name: Create GitHub Release Comment
      if: github.event_name == 'release'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.payload.release.id,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🎉 TypeScript package successfully published to NPM!\n\n📦 Install: `npm install niflheim-x`\n🔗 NPM: https://www.npmjs.com/package/niflheim-x'
          });