name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual trigger for testing
    inputs:
      test_publish:
        description: 'Publish to TestPyPI instead of PyPI'
        required: false
        default: true
        type: boolean

jobs:
  test-publish:
    if: github.event_name == 'workflow_dispatch' && (inputs.test_publish == true || inputs.test_publish == null)
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # For trusted publishing
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
  
  publish:
    if: github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && inputs.test_publish == false)
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # For trusted publishing
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*
    
    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1